"use client";
import React, {useState} from "react";
import {Alert, Button, ColorPicker, Divider, Form} from "antd";
import {CopyOutlined, HomeFilled} from "@ant-design/icons";
import Image from "next/image";
import bgOver from "@/assets/bg_over.jpg";

function hexToRgbA(hex: string): string {
    // Remove the '#' symbol if present
    hex = hex.replace("#", "");

    // Check if the hex value is valid
    if (!/^([A-Fa-f0-9]{3,4}){1,2}$/.test(hex)) {
        throw new Error("Invalid HEX");
    }

    // Convert the hex value to RGBA
    const chunkSize = Math.floor((hex.length - 1) / 3);
    const hexArr = hex.match(new RegExp(`.{${chunkSize}}`, "g"));
    // @ts-ignore
    const [r, g, b, a] = hexArr.map((hexStr) => parseInt(hexStr.repeat(2 / hexStr.length), 16));

    return `Color(${r}, ${g}, ${b}, ${a})`;
}

type IRGB = {
    red: number;
    green: number;
    blue: number;
    alpha: number;
}

type IFields = {
    FRAME_HEADER: any;
    ACTIVITY_BG: any;
    TAB_BAR: any;
    PASSIVE_SELECTIONS: any;
    INNER_SELECTIONS: any;
    SOFT_LINE: any;
    HARD_LINE: any;
    HIGHLIGHTING: any;
    HIGHLIGHT_INACTIVE: any;
    TEXT_HARD: any;
    TEXT_SOFT: any;
    TEXT_ON_HIGHLIGHT: any;
    LOG_SUCCESS: any;
    LOG_ERROR: any;
    LOG_NORMAL: any;
    ICON: any;
};

const recommendedPallete = [
    '#F5222D',
    '#FA8C16',
    '#FADB14',
    '#8BBB11',
    '#52C41A',
    '#13A8A8',
    '#1677FF',
    '#2F54EB',
    '#722ED1',
    '#EB2F96',
]

export default function FormComponent() {
    const [generated, setGenerated] = useState(false);
    const [toCopy,setToCopy] = useState("");
    const [colors,setColors] = useState<any>({
        FRAME_HEADER: "232323",
        HIGHLIGHTING: "1272df",
        ACTIVITY_BG: "161616f0",
        TAB_BAR: "1d1d1d",
        PASSIVE_SELECTIONS: "454545",
        INNER_SELECTIONS: "3e3e3e",
        SOFT_LINE: "4d78a9",
        HARD_LINE: "262626",
        HIGHLIGHT_INACTIVE: "3b3b3b",
        TEXT_HARD: "e2e2e2",
        TEXT_SOFT: "7c7c7c",
        TEXT_ON_HIGHLIGHT: "1272df"});
    async function generateFile(formData: IFields) {
        let prepareString = `-- Theme generated by physgun.ru tools.\n`;
        prepareString += `\nIGS.S.COLORS.FRAME_HEADER = ${hexToRgbA(typeof(formData.FRAME_HEADER) === "string" ? "#fbafff" : "#" + formData.FRAME_HEADER.toHex())}`
        prepareString += `\nIGS.S.COLORS.HIGHLIGHTING = ${hexToRgbA(typeof(formData.HIGHLIGHTING) === "string" ? "#fbafff" : "#" + formData.HIGHLIGHTING.toHex())}`
        prepareString += `\nIGS.S.COLORS.ACTIVITY_BG = ${hexToRgbA(typeof(formData.ACTIVITY_BG) === "string" ? "#fbafff" : "#" + formData.ACTIVITY_BG.toHex())}`
        prepareString += `\nIGS.S.COLORS.TAB_BAR = ${hexToRgbA(typeof(formData.TAB_BAR) === "string" ? "#fbafff" : "#" + formData.TAB_BAR.toHex())}`
        prepareString += `\nIGS.S.COLORS.PASSIVE_SELECTIONS = ${hexToRgbA(typeof(formData.PASSIVE_SELECTIONS) === "string" ? "#fbafff" : "#" + formData.PASSIVE_SELECTIONS.toHex())}`
        prepareString += `\nIGS.S.COLORS.INNER_SELECTIONS = ${hexToRgbA(typeof(formData.INNER_SELECTIONS) === "string" ? "#fbafff" : "#" + formData.INNER_SELECTIONS.toHex())}`
        prepareString += `\nIGS.S.COLORS.SOFT_LINE = ${hexToRgbA(typeof(formData.SOFT_LINE) === "string" ? "#fbafff" : "#" + formData.SOFT_LINE.toHex())}`
        prepareString += `\nIGS.S.COLORS.HARD_LINE = ${hexToRgbA(typeof(formData.HARD_LINE) === "string" ? "#fbafff" : "#" + formData.HARD_LINE.toHex())}`
        prepareString += `\nIGS.S.COLORS.HIGHLIGHT_INACTIVE = ${hexToRgbA(typeof(formData.HIGHLIGHT_INACTIVE) === "string" ? "#fbafff" : "#" + formData.HIGHLIGHT_INACTIVE.toHex())}`
        prepareString += `\nIGS.S.COLORS.TEXT_HARD = ${hexToRgbA(typeof(formData.TEXT_HARD) === "string" ? "#fbafff" : "#" + formData.TEXT_HARD.toHex())}`
        prepareString += `\nIGS.S.COLORS.TEXT_SOFT = ${hexToRgbA(typeof(formData.TEXT_SOFT) === "string" ? "#fbafff" : "#" + formData.TEXT_SOFT.toHex())}`
        prepareString += `\nIGS.S.COLORS.TEXT_ON_HIGHLIGHT = ${hexToRgbA(typeof(formData.TEXT_ON_HIGHLIGHT) === "string" ? "#fbafff" : "#" + formData.TEXT_ON_HIGHLIGHT.toHex())}`
        setGenerated(false);
        setToCopy(prepareString)
        setGenerated(true);
    }

    function rerenderTheme(all: any[],formData: any[]) {
        all.map((col, _)=> {
            if (typeof(col.value) === "object") {
                setColors({...colors, [col.name[0]]: col.value.toHex()})
            } else {
                setColors({...colors, [col.name[0]]: col.value})
            }
        })
    }

    const textWithBreaks = toCopy
        .replace(/"([^"]+)"/g, '<span class="text-yellow-100">$&</span>')
        .replace(/--(.*)/g, '<span class="text-neutral-600">--$1</span>').split('\n').map((text, index) => (
            <React.Fragment key={index}>
                <div dangerouslySetInnerHTML={{__html:text}}/>
            </React.Fragment>
        ));

    return (
        <>
            <Form
                name="theme.gmd"
                initialValues={{
                    FRAME_HEADER: "#232323",
                    HIGHLIGHTING: "#1272df",
                    ACTIVITY_BG: "#161616f0",
                    TAB_BAR: "#1d1d1d",
                    PASSIVE_SELECTIONS: "#454545",
                    INNER_SELECTIONS: "#3e3e3e",
                    SOFT_LINE: "#4d78a9",
                    HARD_LINE: "#262626",
                    HIGHLIGHT_INACTIVE: "#3b3b3b",
                    TEXT_HARD: "#e2e2e2",
                    TEXT_SOFT: "#7c7c7c",
                    TEXT_ON_HIGHLIGHT: "#0077ff"
            }}
                autoComplete="off"
                onFieldsChange={rerenderTheme}
                onFinish={generateFile}
                layout="vertical"
            >
                <Divider className={"my-3"} orientation="left">Цвета</Divider>
                <div className="flex flex-row w-100 gap-5 flex-wrap">
                        <Form.Item<IFields>
                            name="FRAME_HEADER"
                            style={{height: 2}}
                            rules={[{ required: true, message: 'Пожалуйста укажите цвет заголовка' }]}
                        >
                            <ColorPicker
                                showText={(color) => <span>Фон верхушки фреймов</span>}
                                presets={[ { label: 'Рекомендуем', colors: recommendedPallete, } ]}
                                />
                        </Form.Item>
                    <Form.Item<IFields>
                        name="HIGHLIGHTING"
                        style={{height: 2}}
                        rules={[{ required: true, message: 'Пожалуйста укажите цвет заголовка' }]}
                    >
                        <ColorPicker
                            showText={(color) => <span>Обводка кнопок</span>}
                            presets={[ { label: 'Рекомендуем', colors: recommendedPallete, } ]}
                        />
                    </Form.Item>
                        <Form.Item<IFields>
                            name="ACTIVITY_BG"
                            style={{height: 2}}
                            rules={[{ required: true, message: 'Пожалуйста укажите цвет заголовка' }]}
                        >
                            <ColorPicker
                                showText={(color) => <span>Фон в каждой вкладке (основной)</span>}
                                presets={[ { label: 'Рекомендуем', colors: recommendedPallete, } ]}
                                />
                        </Form.Item>
                        <Form.Item<IFields>
                            name="TAB_BAR"
                            style={{height: 2}}
                            rules={[{ required: true, message: 'Пожалуйста укажите цвет заголовка' }]}
                        >
                            <ColorPicker
                                showText={(color) => <span>Фон таб бара</span>}
                                presets={[ { label: 'Рекомендуем', colors: recommendedPallete, } ]}
                            />
                        </Form.Item>
                        <Form.Item<IFields>
                            name="PASSIVE_SELECTIONS"
                            style={{height: 2}}
                            rules={[{ required: true, message: 'Пожалуйста укажите цвет заголовка' }]}
                        >
                            <ColorPicker
                                showText={(color) => <span>Фон панели тегов</span>}
                                presets={[ { label: 'Рекомендуем', colors: recommendedPallete, } ]}
                            />
                        </Form.Item>
                        <Form.Item<IFields>
                            name="INNER_SELECTIONS"
                            style={{height: 2}}
                            rules={[{ required: true, message: 'Пожалуйста укажите цвет заголовка' }]}
                        >
                            <ColorPicker
                                showText={(color) => <span>Фон иконок на плашках</span>}
                                presets={[ { label: 'Рекомендуем', colors: recommendedPallete, } ]}
                            />
                        </Form.Item>
                        <Form.Item<IFields>
                            name="SOFT_LINE"
                            style={{height: 2}}
                            rules={[{ required: true, message: 'Пожалуйста укажите цвет заголовка' }]}
                        >
                            <ColorPicker
                                showText={(color) => <span>Линия между секциями</span>}
                                presets={[ { label: 'Рекомендуем', colors: recommendedPallete, } ]}
                            />
                        </Form.Item>
                        <Form.Item<IFields>
                            name="HARD_LINE"
                            style={{height: 2}}
                            rules={[{ required: true, message: 'Пожалуйста укажите цвет заголовка' }]}
                        >
                            <ColorPicker
                                showText={(color) => <span>Обводки панелей</span>}
                                presets={[ { label: 'Рекомендуем', colors: recommendedPallete, } ]}
                            />
                        </Form.Item>
                        <Form.Item<IFields>
                            name="HIGHLIGHT_INACTIVE"
                            style={{height: 2}}
                            rules={[{ required: true, message: 'Пожалуйста укажите цвет заголовка' }]}
                        >
                            <ColorPicker
                                showText={(color) => <span>Цвет иконки неактивной кнопки таббара</span>}
                                presets={[ { label: 'Рекомендуем', colors: recommendedPallete, } ]}
                            />
                        </Form.Item>
                        <Form.Item<IFields>
                            name="TEXT_HARD"
                            style={{height: 2}}
                            rules={[{ required: true, message: 'Пожалуйста укажите цвет заголовка' }]}
                        >
                            <ColorPicker
                                showText={(color) => <span>Заголовки</span>}
                                presets={[ { label: 'Рекомендуем', colors: recommendedPallete, } ]}
                            />
                        </Form.Item>
                        <Form.Item<IFields>
                            name="TEXT_SOFT"
                            style={{height: 2}}
                            rules={[{ required: true, message: 'Пожалуйста укажите цвет заголовка' }]}
                        >
                            <ColorPicker
                                showText={(color) => <span>Описания</span>}
                                presets={[ { label: 'Рекомендуем', colors: recommendedPallete, } ]}
                            />
                        </Form.Item>
                        <Form.Item<IFields>
                            name="TEXT_ON_HIGHLIGHT"
                            style={{height: 2}}
                            rules={[{ required: true, message: 'Пожалуйста укажите цвет заголовка' }]}
                        >
                            <ColorPicker
                                showText={(color) => <span>Цвет текста на выделенных кнопках</span>}
                                presets={[ { label: 'Рекомендуем', colors: recommendedPallete, } ]}
                            />
                        </Form.Item>
                </div>
                <div className="flex flex-row-reverse mt-5">
                    <Form.Item className={"m-0 p-0"}>
                        <Button type="primary" htmlType="submit" size={"large"} className={"bg-blue-600"}>
                            Создать код
                        </Button>
                    </Form.Item>
                </div>
            </Form>
            <Divider className={"my-3"} orientation="left">Предпросмотр</Divider>
            <div className={"bg-neutral-950 w-100 p-5 rounded-lg relative overflow-hidden"}>
                <Image src={bgOver} alt={"Фон для тестовов"} className={"absolute top-0 left-0 w-full h-full blur-[3px]"}/>
                <div className={"z-20 relative flex flex-col rounded-md overflow-hidden border"} style={{background: "transparent", borderColor: colors["HARD_LINE"] ? "#"+colors["HARD_LINE"] : "#fff"}}>
                    <div className={"flex flex-row ps-5 gap-1"} style={{background: colors["FRAME_HEADER"] ? "#"+colors["FRAME_HEADER"] : "#fff"}}>
                        <div className={"rounded-md border px-3 font-semibold"} style={{borderColor: colors["HIGHLIGHTING"] ? "#"+colors["HIGHLIGHTING"] : "#fff", color: colors["TEXT_ON_HIGHLIGHT"] ? "#"+colors["TEXT_ON_HIGHLIGHT"] : "#000", borderRadius: "4px 4px 0 0", borderBottom: 0, background: colors["PASSIVE_SELECTIONS"] ? "#"+colors["PASSIVE_SELECTIONS"] : "#fff"}}>Баланс: 131 Руб</div>
                        <div className={"px-2 font-semibold"} style={{background: colors["HIGHLIGHTING"] ? "#"+colors["HIGHLIGHTING"] : "#fff", marginTop: 1, borderRadius: "4px 4px 0 0",}}>+</div>
                    </div>
                    <div className={"flex flex-row"}>
                        <div className={"flex flex-col flex-1 border-e"} style={{borderColor: colors["HARD_LINE"] ? "#"+colors["HARD_LINE"] : "#fff",paddingRight: -1}}>
                            <div className={"flex flex-col gap-1"} >
                                <div className={"flex flex-row p-1 gap-3 border"} style={{borderColor: colors["HARD_LINE"] ? "#"+colors["HARD_LINE"] : "#fff",background: colors["PASSIVE_SELECTIONS"] ? "#"+colors["PASSIVE_SELECTIONS"] : "#fff"}}>
                                    <div className={"px-2"} style={{background: colors["HIGHLIGHTING"] ? "#"+colors["HIGHLIGHTING"] : "#fff", borderRadius: 4, color: "#ffffff"}}>Сброс фильтров</div>
                                    <div className={"border px-2"} style={{borderColor: colors["HIGHLIGHTING"] ? "#"+colors["HIGHLIGHTING"] : "#fff", borderRadius: 4, color: colors["TEXT_ON_HIGHLIGHT"] ? "#"+colors["TEXT_ON_HIGHLIGHT"] : "#000"}}>Привилегии</div>
                                    <div className={"border px-2"} style={{borderColor: colors["HIGHLIGHTING"] ? "#"+colors["HIGHLIGHTING"] : "#fff", borderRadius: 4, color: colors["TEXT_ON_HIGHLIGHT"] ? "#"+colors["TEXT_ON_HIGHLIGHT"] : "#000"}}>Дополнительные услуги</div>
                                </div>
                            </div>
                            <div className={"flex-col p-3"} style={{background: colors["ACTIVITY_BG"] ? "#"+colors["ACTIVITY_BG"] : "#fff"}}>
                                <p className={"text-[20px] font-semibold"} style={{color: colors["TEXT_HARD"] ? "#"+colors["TEXT_HARD"] : "#000"}}>Дополнительные услуги</p>
                                <div className={"inline-grid grid-cols-3 gap-3 w-full"}>
                                    <div className={"border p-1 w-full"} style={{borderColor: colors["HARD_LINE"] ? "#"+colors["HARD_LINE"] : "#fff", borderRadius: 4, color: "#d8d8d8",background: colors["INNER_SELECTIONS"] ? "#"+colors["INNER_SELECTIONS"] : "#fff"}}>
                                        <div className="flex flex-row gap-3">
                                            <div className={"w-[50px] h-[50px] border"} style={{borderColor: colors["HARD_LINE"] ? "#"+colors["HARD_LINE"] : "#fff", borderRadius: 4, color: "#d8d8d8"}}></div>
                                            <div className="flex flex-col">
                                                <p className={"text-[16px] font-semibold"} style={{color: colors["TEXT_HARD"] ? "#"+colors["TEXT_HARD"] : "#000"}}>Уровень</p>
                                                <p className={"text-[13px]"} style={{color:colors["TEXT_SOFT"] ? "#"+colors["TEXT_SOFT"] : "#fff"}}>3 варианта</p>
                                            </div>
                                        </div>
                                        <hr className={"mt-2 mx-2"} style={{borderColor: colors["HARD_LINE"] ? "#"+colors["HARD_LINE"] : "#fff"}}/>
                                        <p className={"text-center text-[13px]"} style={{color:colors["TEXT_SOFT"] ? "#"+colors["TEXT_SOFT"] : "#fff"}}>От 60 до 180 Руб</p>
                                    </div>
                                    <div className={"border p-1 w-full"} style={{borderColor: colors["HARD_LINE"] ? "#"+colors["HARD_LINE"] : "#fff", borderRadius: 4, color: "#d8d8d8",background: colors["INNER_SELECTIONS"] ? "#"+colors["INNER_SELECTIONS"] : "#fff"}}>
                                        <div className="flex flex-row gap-3">
                                            <div className={"w-[50px] h-[50px] border"} style={{borderColor: colors["HARD_LINE"] ? "#"+colors["HARD_LINE"] : "#fff", borderRadius: 4, color: "#d8d8d8"}}></div>
                                            <div className="flex flex-col">
                                                <p className={"text-[16px] font-semibold"} style={{color: colors["TEXT_HARD"] ? "#"+colors["TEXT_HARD"] : "#000"}}>Уровень</p>
                                                <p className={"text-[13px]"} style={{color:colors["TEXT_SOFT"] ? "#"+colors["TEXT_SOFT"] : "#fff"}}>3 варианта</p>
                                            </div>
                                        </div>
                                        <hr className={"mt-2 mx-2"} style={{borderColor: colors["HARD_LINE"] ? "#"+colors["HARD_LINE"] : "#fff"}}/>
                                        <p className={"text-center text-[13px]"} style={{color:colors["TEXT_SOFT"] ? "#"+colors["TEXT_SOFT"] : "#fff"}}>От 60 до 180 Руб</p>
                                    </div>
                                    <div className={"border p-1 w-full"} style={{borderColor: colors["HARD_LINE"] ? "#"+colors["HARD_LINE"] : "#fff", borderRadius: 4, color: "#d8d8d8",background: colors["INNER_SELECTIONS"] ? "#"+colors["INNER_SELECTIONS"] : "#fff"}}>
                                        <div className="flex flex-row gap-3">
                                            <div className={"w-[50px] h-[50px] border"} style={{borderColor: colors["HARD_LINE"] ? "#"+colors["HARD_LINE"] : "#fff", borderRadius: 4, color: "#d8d8d8"}}></div>
                                            <div className="flex flex-col">
                                                <p className={"text-[16px] font-semibold"} style={{color: colors["TEXT_HARD"] ? "#"+colors["TEXT_HARD"] : "#000"}}>Уровень</p>
                                                <p className={"text-[13px]"} style={{color:colors["TEXT_SOFT"] ? "#"+colors["TEXT_SOFT"] : "#fff"}}>3 варианта</p>
                                            </div>
                                        </div>
                                        <hr className={"mt-2 mx-2"} style={{borderColor: colors["HARD_LINE"] ? "#"+colors["HARD_LINE"] : "#fff"}}/>
                                        <p className={"text-center text-[13px]"} style={{color:colors["TEXT_SOFT"] ? "#"+colors["TEXT_SOFT"] : "#fff"}}>От 60 до 180 Руб</p>
                                    </div>
                                    <div className={"border p-1 w-full"} style={{borderColor: colors["HARD_LINE"] ? "#"+colors["HARD_LINE"] : "#fff", borderRadius: 4, color: "#d8d8d8",background: colors["INNER_SELECTIONS"] ? "#"+colors["INNER_SELECTIONS"] : "#fff"}}>
                                        <div className="flex flex-row gap-3">
                                            <div className={"w-[50px] h-[50px] border"} style={{borderColor: colors["HARD_LINE"] ? "#"+colors["HARD_LINE"] : "#fff", borderRadius: 4, color: "#d8d8d8"}}></div>
                                            <div className="flex flex-col">
                                                <p className={"text-[16px] font-semibold"} style={{color: colors["TEXT_HARD"] ? "#"+colors["TEXT_HARD"] : "#000"}}>Уровень</p>
                                                <p className={"text-[13px]"} style={{color:colors["TEXT_SOFT"] ? "#"+colors["TEXT_SOFT"] : "#fff"}}>3 варианта</p>
                                            </div>
                                        </div>
                                        <hr className={"mt-2 mx-2"} style={{borderColor: colors["HARD_LINE"] ? "#"+colors["HARD_LINE"] : "#fff"}}/>
                                        <p className={"text-center text-[13px]"} style={{color:colors["TEXT_SOFT"] ? "#"+colors["TEXT_SOFT"] : "#fff"}}>От 60 до 180 Руб</p>
                                    </div>
                                    <div className={"border p-1 w-full"} style={{borderColor: colors["HARD_LINE"] ? "#"+colors["HARD_LINE"] : "#fff", borderRadius: 4, color: "#d8d8d8",background: colors["INNER_SELECTIONS"] ? "#"+colors["INNER_SELECTIONS"] : "#fff"}}>
                                        <div className="flex flex-row gap-3">
                                            <div className={"w-[50px] h-[50px] border"} style={{borderColor: colors["HARD_LINE"] ? "#"+colors["HARD_LINE"] : "#fff", borderRadius: 4, color: "#d8d8d8"}}></div>
                                            <div className="flex flex-col">
                                                <p className={"text-[16px] font-semibold"} style={{color: colors["TEXT_HARD"] ? "#"+colors["TEXT_HARD"] : "#000"}}>Уровень</p>
                                                <p className={"text-[13px]"} style={{color:colors["TEXT_SOFT"] ? "#"+colors["TEXT_SOFT"] : "#fff"}}>3 варианта</p>
                                            </div>
                                        </div>
                                        <hr className={"mt-2 mx-2"} style={{borderColor: colors["HARD_LINE"] ? "#"+colors["HARD_LINE"] : "#fff"}}/>
                                        <p className={"text-center text-[13px]"} style={{color:colors["TEXT_SOFT"] ? "#"+colors["TEXT_SOFT"] : "#fff"}}>От 60 до 180 Руб</p>
                                    </div>
                                    <div className={"border p-1 w-full"} style={{borderColor: colors["HARD_LINE"] ? "#"+colors["HARD_LINE"] : "#fff", borderRadius: 4, color: "#d8d8d8",background: colors["INNER_SELECTIONS"] ? "#"+colors["INNER_SELECTIONS"] : "#fff"}}>
                                        <div className="flex flex-row gap-3">
                                            <div className={"w-[50px] h-[50px] border"} style={{borderColor: colors["HARD_LINE"] ? "#"+colors["HARD_LINE"] : "#fff", borderRadius: 4, color: "#d8d8d8"}}></div>
                                            <div className="flex flex-col">
                                                <p className={"text-[16px] font-semibold"} style={{color: colors["TEXT_HARD"] ? "#"+colors["TEXT_HARD"] : "#000"}}>Уровень</p>
                                                <p className={"text-[13px]"} style={{color:colors["TEXT_SOFT"] ? "#"+colors["TEXT_SOFT"] : "#fff"}}>3 варианта</p>
                                            </div>
                                        </div>
                                        <hr className={"mt-2 mx-2"} style={{borderColor: colors["HARD_LINE"] ? "#"+colors["HARD_LINE"] : "#fff"}}/>
                                        <p className={"text-center text-[13px]"} style={{color:colors["TEXT_SOFT"] ? "#"+colors["TEXT_SOFT"] : "#fff"}}>От 60 до 180 Руб</p>
                                    </div>
                                    <div className={"border p-1 w-full"} style={{borderColor: colors["HARD_LINE"] ? "#"+colors["HARD_LINE"] : "#fff", borderRadius: 4, color: "#d8d8d8",background: colors["INNER_SELECTIONS"] ? "#"+colors["INNER_SELECTIONS"] : "#fff"}}>
                                        <div className="flex flex-row gap-3">
                                            <div className={"w-[50px] h-[50px] border"} style={{borderColor: colors["HARD_LINE"] ? "#"+colors["HARD_LINE"] : "#fff", borderRadius: 4, color: "#d8d8d8"}}></div>
                                            <div className="flex flex-col">
                                                <p className={"text-[16px] font-semibold"} style={{color: colors["TEXT_HARD"] ? "#"+colors["TEXT_HARD"] : "#000"}}>Уровень</p>
                                                <p className={"text-[13px]"} style={{color:colors["TEXT_SOFT"] ? "#"+colors["TEXT_SOFT"] : "#fff"}}>3 варианта</p>
                                            </div>
                                        </div>
                                        <hr className={"mt-2 mx-2"} style={{borderColor: colors["HARD_LINE"] ? "#"+colors["HARD_LINE"] : "#fff"}}/>
                                        <p className={"text-center text-[13px]"} style={{color:colors["TEXT_SOFT"] ? "#"+colors["TEXT_SOFT"] : "#fff"}}>От 60 до 180 Руб</p>
                                    </div>
                                    <div className={"border p-1 w-full"} style={{borderColor: colors["HARD_LINE"] ? "#"+colors["HARD_LINE"] : "#fff", borderRadius: 4, color: "#d8d8d8",background: colors["INNER_SELECTIONS"] ? "#"+colors["INNER_SELECTIONS"] : "#fff"}}>
                                        <div className="flex flex-row gap-3">
                                            <div className={"w-[50px] h-[50px] border"} style={{borderColor: colors["HARD_LINE"] ? "#"+colors["HARD_LINE"] : "#fff", borderRadius: 4, color: "#d8d8d8"}}></div>
                                            <div className="flex flex-col">
                                                <p className={"text-[16px] font-semibold"} style={{color: colors["TEXT_HARD"] ? "#"+colors["TEXT_HARD"] : "#000"}}>Уровень</p>
                                                <p className={"text-[13px]"} style={{color:colors["TEXT_SOFT"] ? "#"+colors["TEXT_SOFT"] : "#fff"}}>3 варианта</p>
                                            </div>
                                        </div>
                                        <hr className={"mt-2 mx-2"} style={{borderColor: colors["HARD_LINE"] ? "#"+colors["HARD_LINE"] : "#fff"}}/>
                                        <p className={"text-center text-[13px]"} style={{color:colors["TEXT_SOFT"] ? "#"+colors["TEXT_SOFT"] : "#fff"}}>От 60 до 180 Руб</p>
                                    </div>
                                </div>

                                <p className={"text-[20px] font-semibold mt-3"} style={{color: colors["TEXT_HARD"] ? "#"+colors["TEXT_HARD"] : "#000"}}>Привилегии</p>
                                <div className={"inline-grid grid-cols-3 gap-3 w-full"}>
                                    <div className={"border p-1 w-full"} style={{borderColor: colors["HARD_LINE"] ? "#"+colors["HARD_LINE"] : "#fff", borderRadius: 4, color: "#d8d8d8",background: colors["INNER_SELECTIONS"] ? "#"+colors["INNER_SELECTIONS"] : "#fff"}}>
                                        <div className="flex flex-row gap-3">
                                            <div className={"w-[50px] h-[50px] border"} style={{borderColor: colors["HARD_LINE"] ? "#"+colors["HARD_LINE"] : "#fff", borderRadius: 4, color: "#d8d8d8"}}></div>
                                            <div className="flex flex-col">
                                                <p className={"text-[16px] font-semibold"} style={{color: colors["TEXT_HARD"] ? "#"+colors["TEXT_HARD"] : "#000"}}>Уровень</p>
                                                <p className={"text-[13px]"} style={{color:colors["TEXT_SOFT"] ? "#"+colors["TEXT_SOFT"] : "#fff"}}>3 варианта</p>
                                            </div>
                                        </div>
                                        <hr className={"mt-2 mx-2"} style={{borderColor: colors["HARD_LINE"] ? "#"+colors["HARD_LINE"] : "#fff"}}/>
                                        <p className={"text-center text-[13px]"} style={{color:colors["TEXT_SOFT"] ? "#"+colors["TEXT_SOFT"] : "#fff"}}>От 60 до 180 Руб</p>
                                    </div>
                                    <div className={"border p-1 w-full"} style={{borderColor: colors["HARD_LINE"] ? "#"+colors["HARD_LINE"] : "#fff", borderRadius: 4, color: "#d8d8d8",background: colors["INNER_SELECTIONS"] ? "#"+colors["INNER_SELECTIONS"] : "#fff"}}>
                                        <div className="flex flex-row gap-3">
                                            <div className={"w-[50px] h-[50px] border"} style={{borderColor: colors["HARD_LINE"] ? "#"+colors["HARD_LINE"] : "#fff", borderRadius: 4, color: "#d8d8d8"}}></div>
                                            <div className="flex flex-col">
                                                <p className={"text-[16px] font-semibold"} style={{color: colors["TEXT_HARD"] ? "#"+colors["TEXT_HARD"] : "#000"}}>Уровень</p>
                                                <p className={"text-[13px]"} style={{color:colors["TEXT_SOFT"] ? "#"+colors["TEXT_SOFT"] : "#fff"}}>3 варианта</p>
                                            </div>
                                        </div>
                                        <hr className={"mt-2 mx-2"} style={{borderColor: colors["HARD_LINE"] ? "#"+colors["HARD_LINE"] : "#fff"}}/>
                                        <p className={"text-center text-[13px]"} style={{color:colors["TEXT_SOFT"] ? "#"+colors["TEXT_SOFT"] : "#fff"}}>От 60 до 180 Руб</p>
                                    </div>
                                </div>
                            </div>
                            <div className={"flex flex-col gap-1"} >
                                <div className={"flex flex-row py-1 gap-6 justify-center items-center border-t"} style={{borderColor: colors["HARD_LINE"] ? "#"+colors["HARD_LINE"] : "#fff",background: colors["TAB_BAR"] ? "#"+colors["TAB_BAR"] : "#fff"}}>
                                    <div className={"flex flex-col justify-center items-center"} style={{color: colors["HIGHLIGHT_INACTIVE"] ? "#"+colors["HIGHLIGHT_INACTIVE"] : "#fff"}}>
                                        <HomeFilled className={"text-[33px]"} />
                                        <p>Страница</p>
                                    </div>
                                    <div className={"flex flex-col justify-center items-center"} style={{color: colors["HIGHLIGHTING"] ? "#"+colors["HIGHLIGHTING"] : "#fff"}}>
                                        <HomeFilled className={"text-[33px]"} />
                                        <p>Страница</p>
                                    </div>
                                    <div className={"flex flex-col justify-center items-center"} style={{color: colors["HIGHLIGHT_INACTIVE"] ? "#"+colors["HIGHLIGHT_INACTIVE"] : "#fff"}}>
                                        <HomeFilled className={"text-[33px]"} />
                                        <p>Страница</p>
                                    </div>
                                    <div className={"flex flex-col justify-center items-center"} style={{color: colors["HIGHLIGHT_INACTIVE"] ? "#"+colors["HIGHLIGHT_INACTIVE"] : "#fff"}}>
                                        <HomeFilled className={"text-[33px]"} />
                                        <p>Страница</p>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div className={"flex w-1/3 flex-col"} style={{background: colors["ACTIVITY_BG"] ? "#"+colors["ACTIVITY_BG"] : "#fff"}}>
                            <div className={"flex flex-col gap-1"} style={{background: colors["FRAME_HEADER"] ? "#"+colors["FRAME_HEADER"] : "#fff"}}>
                                <p className={"text-center text-lg font-semibold border-b pb-3"} style={{color: colors["TEXT_HARD"] ? "#"+colors["TEXT_HARD"] : "#000",borderColor: colors["HARD_LINE"] ? "#"+colors["HARD_LINE"] : "#fff"}}>Последние покупки</p>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            {generated &&
                <div className="flex flex-col bg-neutral-950 rounded-lg mt-5 p-5 gap-5">
                    <Alert message="Ваш файл успешно создан!" type="success" showIcon />
                    <div className="flex flex-col text-neutral-400">
                        {textWithBreaks}
                    </div>
                    <div className="flex flex-row-reverse gap-2">
                        <Button onClick={() => {navigator.clipboard.writeText(toCopy)}} type="dashed" icon={<CopyOutlined />} size={"large"} />
                    </div>
                </div>
            }
        </>
    )
}
